version: 2.1

orbs:
  android: circleci/android@1.0.2

jobs:
  build:
    executor: android/default
    steps:
      - checkout
      - run:
          name: Set up Java
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            java -version
      - run:
          name: Download Dependencies
          command: |
            ./gradlew androidDependencies
      - save_cache:
          key: android-cache-{{ checksum "app/build.gradle" }}-{{ checksum "app/build.gradle.kts" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - run:
          name: Build APK
          command: |
            ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: debug-apks
  test:
    executor: android/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - android-cache-{{ checksum "app/build.gradle" }}-{{ checksum "app/build.gradle.kts" }}
      - run:
          name: Run Unit Tests
          command: |
            ./gradlew test
  lint:
    executor: android/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - android-cache-{{ checksum "app/build.gradle" }}-{{ checksum "app/build.gradle.kts" }}
      - run:
          name: Run Lint
          command: |
            ./gradlew lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
